backend:
  name: github
  repo: finiam/cryptobrands.finiam.com
  squash_merges: true
publish_mode: editorial_workflow
media_folder: "static/images"
public_folder: "/images"
collections:
  - name: "projects"
    label: "Projects"
    folder: "backend/projects"
    extension: "json"
    create: true
    slug: "{{sort}}_{{title}}"
    summary: "{{sort}}_{{title}}"
    sortable_fields: ["sort"]
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Link Name", name: "linkName", widget: "string" }
      - { label: "Studio Name", name: "studioName", widget: "string", required: false }
      - { label: "Studio Link", name: "studioLink", widget: "string", required: false }
      - { label: "Image", name: "imagePath", widget: "image" }
      - { label: "Number", name: "sort", widget: "number" }
